# Generated by Django 4.0.4 on 2022-09-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
