# Generated by Django 4.0.4 on 2022-09-24 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0002_rename_author_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
