# Generated by Django 4.0.4 on 2022-09-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0003_comment_date_created_comment_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_created']},
        ),
    ]
