# Generated by Django 4.0.4 on 2022-09-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0006_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learnApp.post'),
        ),
    ]
