# Generated by Django 4.0.4 on 2022-09-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0007_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
