# Generated by Django 3.2.15 on 2022-09-30 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0010_auto_20220930_0106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
